In [2]:
import numpy as np
#列表如何转化为ndarray
list1=[1,2,3,4,5,6,7,8,9,10]
nlist=np.array(list1)
print(type(list))
print(type(nlist))

<class 'type'>
<class 'numpy.ndarray'>


In [3]:
#计算效率对比
import random
import time
a = []
for i in range(10**8):
    a.append(random.random())
    
#python内置函数sum计算效率较低  
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
#numpy的sum计算效率较高
t3 = time.time()
sum2 = np.sum(b)
t4 = time.time()

print(t2 - t1, t4 - t3)

0.5396323204040527 0.09050941467285156


In [4]:
#创建一维数组
a = np.array([1,2,3,4,5])
b=np.array(range(10))
c=np.arange(0,10,2)
print(a,type(a))
print(b,type(b))
print(c,type(c))

[1 2 3 4 5] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 2 4 6 8] <class 'numpy.ndarray'>


In [8]:
#创建二维数组
list=[[1,2],[3,4],[5,6]]
twoarray=np.array(list)
print(twoarray)
print('-'*20)
print(twoarray.shape)# 形状
print(twoarray.size)# 元素个数
print(twoarray.dtype)# 数据类型
print(twoarray.ndim)# 数组维度

[[1 2]
 [3 4]
 [5 6]]
--------------------
(3, 2)
6
int64
2


In [19]:
#调整数组形状
list=[1,2,3,4,5,6]
a=np.array(list)
print(a)
print(a.shape)
print('-'*20)
a.shape=(3,2)# a改变
print(a,a.shape)
print('-'*20)
b=a.reshape((2,3))# a不改变 将改变赋给b
print(b,b.shape)
print(a,a.shape)
print('-'*20)
c=b.reshape((6,))
print(c,c.shape)

[1 2 3 4 5 6]
(6,)
--------------------
[[1 2]
 [3 4]
 [5 6]] (3, 2)
--------------------
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
--------------------
[1 2 3 4 5 6] (6,)


In [18]:
#将数组转成list
a=np.array([1,2,3,4,5,6])
print(type(a))
list=a.tolist()
print(list)
print(type(list))

<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
<class 'list'>


In [28]:
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
# 拓展随机生成小数
print(round(random.random(),2))#round()舍入，不传第二个参数时舍入到整数，传2保留两位小数
arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))
print(arr.dtype)
arr1=np.astype(arr,np.float16)
print(arr1.dtype)

2
int16
int64
0.95
[0.83 0.69 0.48 0.31 0.5  0.35 0.73 0.63 0.36 0.95]
float64
float16


In [30]:
#数组和数的计算 广播机制
a=np.arange(6).reshape(2,3)
print(a)
print(a+2)
print(a*2)
print(a/2)
print(a**2)
print('-'*20)
b=a.tolist()
print(b)
print(b+2)#对一般python列表不可操作

[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]
[[ 0  2  4]
 [ 6  8 10]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]]
[[ 0  1  4]
 [ 9 16 25]]
--------------------
[[0, 1, 2], [3, 4, 5]]


TypeError: can only concatenate list (not "int") to list

In [33]:
#数组和数组的运算
#形状相同,才可以进行加减乘除
t1 = np.arange(6).reshape((3, 2))
t2 = np.arange(100, 106).reshape((3, 2))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #不是矩阵乘法 只是逐项相乘

[[0 1]
 [2 3]
 [4 5]]
[[100 101]
 [102 103]
 [104 105]]
--------------------------------------------------
[[100 102]
 [104 106]
 [108 110]]
--------------------------------------------------
[[  0 101]
 [204 309]
 [416 525]]


In [34]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((3, 6))
print(t1)
print(t2)
print(t1 - t2)

ValueError: cannot reshape array of size 6 into shape (3,6)

In [37]:
#一维数组和二维数组进行运算时，一维的 元素个数 和 列数 相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print('-'*10)
print(t2)
print('-'*20)
print(t1 - t2) #逐行减 因此t1第一列均减0 第二列均减1 第三列均减2……

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------
[[0 1 2 3 4 5]]
--------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [38]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print('-'*10)
print(t1)
print('-'*20)
print(t1 - t2) #逐列减 因此第一行均减0，第二行均减1，第三行均减2……

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [40]:
#随机3维数组
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
print(a)
print('-'*10)
print(b)
print('-'*20)
print(a-b) #将维数相同的部分 整体拿来 在维数不同的那根轴上遍历做运算，其中一个ndarray在该轴上维数必须为1

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
----------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
--------------------
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[12 12 12 12]
  [12 12 12 12]
  [12 12 12 12]]]
