In [2]:
import numpy as np
#列表如何转化为ndarray
list1=[1,2,3,4,5,6,7,8,9,10]
nlist=np.array(list1)
print(type(list))
print(type(nlist))

<class 'type'>
<class 'numpy.ndarray'>


In [3]:
#计算效率对比
import random
import time
a = []
for i in range(10**8):
    a.append(random.random())
    
#python内置函数sum计算效率较低  
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
#numpy的sum计算效率较高
t3 = time.time()
sum2 = np.sum(b)
t4 = time.time()

print(t2 - t1, t4 - t3)

0.5396323204040527 0.09050941467285156


In [4]:
#创建一维数组
a = np.array([1,2,3,4,5])
b=np.array(range(10))
c=np.arange(0,10,2)
print(a,type(a))
print(b,type(b))
print(c,type(c))

[1 2 3 4 5] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 2 4 6 8] <class 'numpy.ndarray'>


In [8]:
#创建二维数组
list=[[1,2],[3,4],[5,6]]
twoarray=np.array(list)
print(twoarray)
print('-'*20)
print(twoarray.shape)# 形状
print(twoarray.size)# 元素个数
print(twoarray.dtype)# 数据类型
print(twoarray.ndim)# 数组维度

[[1 2]
 [3 4]
 [5 6]]
--------------------
(3, 2)
6
int64
2


In [19]:
#调整数组形状
list=[1,2,3,4,5,6]
a=np.array(list)
print(a)
print(a.shape)
print('-'*20)
a.shape=(3,2)# a改变
print(a,a.shape)
print('-'*20)
b=a.reshape((2,3))# a不改变 将改变赋给b
print(b,b.shape)
print(a,a.shape)
print('-'*20)
c=b.reshape((6,))
print(c,c.shape)

[1 2 3 4 5 6]
(6,)
--------------------
[[1 2]
 [3 4]
 [5 6]] (3, 2)
--------------------
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
--------------------
[1 2 3 4 5 6] (6,)


In [18]:
#将数组转成list
a=np.array([1,2,3,4,5,6])
print(type(a))
list=a.tolist()
print(list)
print(type(list))

<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
<class 'list'>


In [28]:
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
# 拓展随机生成小数
print(round(random.random(),2))#round()舍入，不传第二个参数时舍入到整数，传2保留两位小数
arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))
print(arr.dtype)
arr1=np.astype(arr,np.float16)
print(arr1.dtype)

2
int16
int64
0.95
[0.83 0.69 0.48 0.31 0.5  0.35 0.73 0.63 0.36 0.95]
float64
float16


In [30]:
#数组和数的计算 广播机制
a=np.arange(6).reshape(2,3)
print(a)
print(a+2)
print(a*2)
print(a/2)
print(a**2)
print('-'*20)
b=a.tolist()
print(b)
print(b+2)#对一般python列表不可操作

[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]
[[ 0  2  4]
 [ 6  8 10]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]]
[[ 0  1  4]
 [ 9 16 25]]
--------------------
[[0, 1, 2], [3, 4, 5]]


TypeError: can only concatenate list (not "int") to list

In [33]:
#数组和数组的运算
#形状相同,才可以进行加减乘除
t1 = np.arange(6).reshape((3, 2))
t2 = np.arange(100, 106).reshape((3, 2))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #不是矩阵乘法 只是逐项相乘

[[0 1]
 [2 3]
 [4 5]]
[[100 101]
 [102 103]
 [104 105]]
--------------------------------------------------
[[100 102]
 [104 106]
 [108 110]]
--------------------------------------------------
[[  0 101]
 [204 309]
 [416 525]]


In [1]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((3, 2))
print(t1)
print(t2)
print(t1 - t2)

NameError: name 'np' is not defined

In [37]:
#一维数组和二维数组进行运算时，一维的 元素个数 和 列数 相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print('-'*10)
print(t2)
print('-'*20)
print(t1 - t2) #逐行减 因此t1第一列均减0 第二列均减1 第三列均减2……

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------
[[0 1 2 3 4 5]]
--------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [38]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print('-'*10)
print(t1)
print('-'*20)
print(t1 - t2) #逐列减 因此第一行均减0，第二行均减1，第三行均减2……

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [40]:
#随机3维数组
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
print(a)
print('-'*10)
print(b)
print('-'*20)
print(a-b) #将维数相同的部分 整体拿来 在维数不同的那根轴上遍历做运算，其中一个ndarray在该轴上维数必须为1

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
----------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
--------------------
[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[12 12 12 12]
  [12 12 12 12]
  [12 12 12 12]]]


In [1]:
#练习轴
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a)) #全部相加
print("-" * 20)

[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------


In [2]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0) 
print("-" * 20)
print(b.shape)#（3，4）
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)#（2，4）
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)#（2，3）

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


In [3]:
#切片和索引
a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2
print(a[2:7:2])
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2])  #切片是左闭右开 8打印不出来

[2 4 6]
0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [7]:
#按行取
t1 = np.arange(24).reshape(4, 6)
print(t1[0:2, 3])
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print(t1[2,:])
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行 左闭右开 取出行1、2
print('*' * 20)
print(t1[[0, 2, 3]])  # 取不连续的多行 两层括号
print('*' * 20)
print(t1[0,2]) # 取0行2列的元素
print('*' * 20)
print(t1[0:2, 3]) #取出0行和1行的列3的元素 即[3,9]

[3 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
2
********************
[3 9]


In [15]:
#列表的情况
t2 = np.arange(24).reshape(4, 6).tolist()
t2[[0, 2, 3]]

TypeError: list indices must be integers or slices, not list

In [19]:
#按列取
print(t1)
print('*'*20)
print(t1[:, 1])  # 取一列
print('*' * 20)
print(t1[:, 1:])  # 连续的多列
print('*' * 20)
print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)
print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)
print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]
print('*'*20)
print(t1[1:3, 1:4])  #取1-3行，1-4列

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]
********************
[[ 7  8  9]
 [13 14 15]]


In [31]:
#修改值
t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# # 修改某一行的值
# t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0 #左闭右开
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0

# 使用逻辑判断
# np.logical_and	& 
# np.logical_or	    |
# np.logical_not	~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	# 逻辑非
# print(t)
t = t.clip(10, 18) # 限制值范围 将小于10的改为10，大于18的改为18
print(id(t))
t

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2850581106960
--------------------------------------------------
2850581325712


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])

In [33]:
#判断条件
t = np.arange(24).reshape(4, 6)
print(t < 10) # 得到一个布尔型数组，元素为True或False

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [34]:
#python的三目运算
a = 10
b = 15
c = a if a > b else b
c

15

In [35]:
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  #类似于if else
print(result)

[[80 88]
 [82 81]
 [75 81]]
[[False False]
 [False False]
 [ True False]]


In [36]:
score[result] = 100 #将score中对应result为True的元素改为100
score  

array([[ 80,  88],
       [ 82,  81],
       [100,  81]])

In [40]:
#数据的添加、删除与去重
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配否则将生成ValueError。
'''
参 数 说 明 ：        
arr： 输 入 数 组 
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）                                                            
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，分别为0和1的时候。
当axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。
'''
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))  #ndarray会被展平
print('-'*20)
b=np.append(a, [7, 8, 9]).reshape(3,3) #同样会被展平，但可以通过reshape恢复原来的维度
print(b) 
print('-'*20)
print(a)
print('-' * 50)

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]
--------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[1 2 3]
 [4 5 6]]
--------------------------------------------------


In [41]:
b = np.array([[7, 8, 9]])#虽然只有一行，但维度为2
print(b.ndim)
print(b)

2
[[7 8 9]]


In [43]:
# 添加 append
a = np.array([[1, 2, 3], [4, 5, 6]])
print('沿轴 0 添加元素：')  #往哪个轴添加，那个轴size就变大
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print(a)
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
print(a)

沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]
沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]


In [46]:
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('-' * 50)
print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 1, [11, 22]))
print('-' * 50)
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print(np.insert(a, 1, [11, 12], axis=0))  #那个轴插入，哪个轴size变大 插在0轴的行1
print('-' * 50)
print('沿轴  0 广播：') #按行插入，行数变大 插在0轴的行1 且行1的元素填满11
print(np.insert(a, 1, 11, axis=0))
print('-' * 50)
print('沿轴  1 广播：') #按列插入，列数变大 插在1轴的列1
print(np.insert(a, 1, [1, 2, 5], axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]
--------------------------------------------------
未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1 11 22  2  3  4  5  6]
--------------------------------------------------
传递了 Axis 参数。 会广播值数组来配输入数组。
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
--------------------------------------------------
沿轴  0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
--------------------------------------------------
沿轴  1 广播：
[[1 1 2]
 [3 2 4]
 [5 5 6]]


In [47]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说 明 ： arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开'''
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a, 5))
print('\n')
print(a)
print('删除第一行：')
print(np.delete(a, 1, axis=0))
print('\n')

print('删除第一列：')
print(np.delete(a, 1, axis=1))

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
删除第一行：
[[ 0  1  2  3]
 [ 8  9 10 11]]


删除第一列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [54]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展平
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])

print('第一个数组：')
print(a)
print('\n')

#去除重复元素，输出的是有序序列
# print ('第一个数组的去重值：')
# u = np.unique(a)
# print (u)
# print ('\n')

# print ('去重数组的索引数组：')
# u,indices = np.unique(a, return_index = True)
# print(u) #去重后的数组
# print (indices) #留下的每个元素在原数组中的下标
# print ('\n')

# print ('我们可以看到每个和原数组下标对应的数值：')
# print ('去重数组的下标：')
# u,indices = np.unique(a,return_inverse = True)
# print (u) #去重后的数组
# print (indices) #原数组中每个元素在去重后的数组中的下标

# print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_counts=True)
print(u) #去重后的数组
print(indices) #去重后的数组中每个元素在原数组中的出现次数

第一个数组：
[5 2 6 2 7 5 6 9 8 2]


[2 5 6 7 8 9]
[3 2 2 1 1 1]


# numpy中的数学计算

In [58]:
import numpy as np

score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
print('-'*20)
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
print('-'*20)
# 2. 获取某一个轴上的数据最大值，对应的轴就消失
result = np.max(score, axis=1) # 求每一行的最大值，返回一维数组 轴1方向上的一个样本即是一行 沿轴1方向求每个样本的最大值 即求每一行的最大值
print(result)
print('-'*20)
# 3. 获取最小值
result = np.min(score)
print(result)
print('-'*20)
# 4. 获取某一个轴上的数据最小值
result = np.min(score, axis=0)
print(result)
print('-'*20)
# 5. 数据的比较
result = np.maximum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
print('-'*20)
result = np.minimum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
print('-'*20)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)

[[80 88]
 [82 81]
 [75 81]]
--------------------
88
--------------------
[88 82 81]
--------------------
75
--------------------
[75 81]
--------------------
[0 0 0 1 2]
--------------------
[-2 -1  0  0  0]
--------------------
[1 2 4 4 5]


In [ ]:
'''
通用函数：
numpy.sqrt(array)	平方根函数
numpy.exp(array)	e^array[i]的数组
numpy.abs/fabs(array)	计算绝对值
numpy.square(array)	计算各元素的平方 等于array	2
numpy.log/log10/log2(array)	计算各元素的各种对数
numpy.sign(array)	计算各元素正负号
numpy.isnan(array)	计算各元素是否为NaN
numpy.isinf(array)	计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
numpy.ceil(array)	向上取整,也就是取比这个数大的整数
numpy.floor(array)	向下取整,也就是取比这个数小的整数
numpy.rint(array)	四舍五入
numpy.trunc(array)	向0取整
numpy.cos(array)	正弦值
numpy.sin(array)	余弦值
numpy.tan(array)	正切值

numpy.add(array1,array2)	元素级加法
numpy.subtract(array1,array2)	元素级减法
numpy.multiply(array1,array2)	元素级乘法
numpy.divide(array1,array2)	元素级除法 array1./array2
numpy.power(array1,array2)	元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
numpy.mod(array1,array2)	元素级求模
numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''